# Generated by Django 3.2.4 on 2023-12-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alumno_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Libro', models.CharField(max_length=255)),
                ('Autor', models.CharField(max_length=255)),
                ('Edicion', models.CharField(max_length=50)),
                ('Editorial', models.CharField(max_length=100)),
            ],
        ),
    ]
