# Generated by Django 3.2.4 on 2023-12-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros_imagenes/'),
        ),
    ]
