# Generated by Django 3.2.4 on 2023-12-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_libro_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='exit', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
